apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-panel
  labels:
    app: admin-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-panel
  template:
    metadata:
      labels:
        app: admin-panel
    spec:
      containers:
      - name: admin
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: admin-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: admin-html
        configMap:
          name: admin-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Admin Panel - Kubernetes Learning</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .container { max-width: 800px; margin: 0 auto; }
            .header { background: #2c3e50; color: white; padding: 20px; border-radius: 5px; }
            .content { margin-top: 20px; }
            .status { padding: 10px; border-radius: 5px; margin: 10px 0; }
            .success { background: #d4edda; border: 1px solid #c3e6cb; color: #155724; }
            .info { background: #d1ecf1; border: 1px solid #bee5eb; color: #0c5460; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🚀 Kubernetes Learning Project - Admin Panel</h1>
                <p>Phase 4: Ingress Controllers & Advanced Networking</p>
            </div>
            <div class="content">
                <div class="status success">
                    <h3>✅ Ingress Controller Working!</h3>
                    <p>This page is served through the Ingress controller with path-based routing.</p>
                </div>
                <div class="status info">
                    <h3>📚 Learning Progress:</h3>
                    <ul>
                        <li>✅ Phase 1: Basic Deployments</li>
                        <li>✅ Phase 2: ConfigMaps & Secrets</li>
                        <li>✅ Phase 3: Persistent Volumes & StatefulSets</li>
                        <li>🔄 Phase 4: Ingress Controllers & Advanced Networking</li>
                    </ul>
                </div>
                <div class="status info">
                    <h3>🔗 Available Services:</h3>
                    <ul>
                        <li><a href="/">FastAPI Application</a> - Main API</li>
                        <li><a href="/health">Health Check</a> - API Health</li>
                        <li><a href="/items/">Items API</a> - Database Operations</li>
                    </ul>
                </div>
            </div>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin-panel
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: admin-panel 