apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: kubernetes-learning
  labels:
    app: fastapi
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
      version: v1
  template:
    metadata:
      labels:
        app: fastapi
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: fastapi
        image: fastapi-mongo-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: fastapi-config
              key: MONGO_HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: fastapi-config
              key: MONGO_PORT
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: fastapi-config
              key: MONGO_DB
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_USER
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_PASS
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: kubernetes-learning
  labels:
    app: fastapi
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: fastapi 