apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # These are base64 encoded values
  # To generate: echo -n "your_username" | base64
  # To generate: echo -n "your_password" | base64
  MONGO_USER: YWRtaW4=  # "admin" in base64
  MONGO_PASS: cGFzc3dvcmQxMjM=  # "password123" in base64 